### ISSUE TITLE
Trigger Ad manually Demo doesn't work

### ISSUE THREAD

**Issue by tigitz** [openplayerjs/openplayerjs#214]
**Describe the bug**
Ad plays at the start when it shouldn't and Play ad button that supposed to start the ad manually doesn't work either

**To Reproduce**
https://codepen.io/rafa8626/pen/abZNgoY

**Comment by rafa8626** [comment]
@tigitz thanks for reporting this; I'll look at it and let you know when I have the fix ready

**Comment by rafa8626** [comment]
@tigitz Please download the master branch; it should be fixed with #213

**Comment by tigitz** [comment]
@rafa8626 Thanks !

It seems though that the `Play Ad` button still doesn't work

https://codepen.io/tigitz/pen/yLVxWEy (it uses master)

**Comment by rafa8626** [comment]
@tigitz the only thing missing with the button is: 
```javascript
 playAdBtn.addEventListener('click', playAd);
```

**Comment by mikheilangel** [comment]
Excuse me, in this code generator, "Your media URL" and "Ads URL" can also work with only .mp3 audio files? I tried but it only listens to the first link. Thank you.
![media-settings](https://user-images.githubusercontent.com/65021747/110354340-56ef9d80-8038-11eb-86f5-df888769e02b.png)

**Comment by rafa8626** [comment]
@mikheilangel it works with MP3, MP4, M3U8 and MPD files

**Comment by rafa8626** [comment]
@mikheilangel yes, it works. Just set the URL and then check the audio one and hit Load.
<img width="1170" alt="Screen Shot 2021-03-08 at 7 40 59 PM" src="https://user-images.githubusercontent.com/910829/110400813-5a8a2100-8046-11eb-9473-d2af2f8f6669.png">

**Comment by mikheilangel** [comment]
"Your media URL" works, but "Ads URL" doesn't start. 
I would like that when you click play, you must first listen to the mp3 link contained in "Ads URL" and then the mp3 link contained in "Your media URL" in sequence.

**Comment by rafa8626** [comment]
@mikheilangel  ok I’ll check it and keep you posted

**Comment by rafa8626** [comment]
@mikheilangel I checked this and it worked as expected; I used `https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=` as an example with the audio and I see the ad playing first and then the audio after clicking play
<img width="976" alt="Screen Shot 2021-03-13 at 2 49 40 PM" src="https://user-images.githubusercontent.com/910829/111042461-88d37c00-840b-11eb-8398-7195cb44e7bd.png">
<img width="982" alt="Screen Shot 2021-03-13 at 2 49 52 PM" src="https://user-images.githubusercontent.com/910829/111042462-88d37c00-840b-11eb-8117-4ea2e031eda1.png">

**Comment by mikheilangel** [comment]
@rafa8626 first sorry for the late reply. 
Yes I have tried with your link and I have heard that it works regularly, but I don't understand how I have to go to have a link like the one you used.
If I wanted to use my link where I upload my file, it can't work right?
Thanks for your patience.

**Comment by rafa8626** [comment]
@mikheilangel this will only work with an external URL, not with one with a `file://` protocol, or with a local path. So if you store your file in Dropbox, S3, etc., it should be able to reproduce it, unless there are CORS involved and the media cannot play

**Comment by mikheilangel** [comment]
@rafa8626 i also tried with 2 audio links on dropbox, but unfortunately i can't get it to work.
https://www.dropbox.com/s/qhvb6ehvlp5urnb/overture.mp3?dl=0
https://www.dropbox.com/s/9qu4t7ruxh0wnch/overture.wav?dl=0
I don't know, maybe I'm the one who's doing something wrong. Thanks anyway.

**Comment by rafa8626** [comment]
@mikheilangel the problem with DropBox is that it is not a straight MP3/WAV source: it's an HTML page and that's why you can't play them directly from there
