### ISSUE TITLE
Player freeze in iOS < 14

### ISSUE THREAD

**Issue by tigitz** [openplayerjs/openplayerjs#215]
**Describe the bug**
Might be related to https://github.com/openplayerjs/openplayerjs/issues/213 but on iOS before version 14, the player freeze when clicking on play button.

**To Reproduce**
https://codesandbox.io/s/epic-meitner-tzdyh?file=/package.json:291-297

https://user-images.githubusercontent.com/1524501/110227744-cf047900-7efb-11eb-9531-92439376558d.mp4

https://user-images.githubusercontent.com/1524501/110227755-e2174900-7efb-11eb-8d73-e30af2a659eb.mp4

I can share my https://app.lambdatest.com/ account if it can help you work on this

**Comment by rafa8626** [comment]
@tigitz Can you download the master branch and confirm this is fixed, please? If not, I'll ask you to share your account to troubleshoot this. I'm almost confident that the fix I just put in place will help but I wanna make sure you are not seeing another issue in those environments

**Comment by tigitz** [comment]
Hey @rafa8626 ! thanks.

Tried `master` branch but doesnt seem to fix this particular issue: https://codesandbox.io/s/loving-ramanujan-q0i2f?file=/index.html

I'll share the simulator credentials on your gmail email if that's ok to assist you.

**Comment by rafa8626** [comment]
@tigitz I checked in Browserstack, because when I tried to use LambdaTest I just had access to iOS 14; so I tried in iOS 13 and all was fine. This is my recording

https://user-images.githubusercontent.com/910829/110271805-ba28f380-7f96-11eb-814b-3d1608aa2327.mp4

**Comment by tigitz** [comment]
Indeed, I guess it comes down to LambdaTest using Simulator while BrowserStack is using real hardware / VM

Sorry for the bother

**Comment by rafa8626** [comment]
No worries. Glad it is not a bug
