### ISSUE TITLE
Event listeners on destroy

### ISSUE THREAD

**Issue by draganpetos** [openplayerjs/openplayerjs#253]
Not all event listeners get removed when destroying the player.

Steps to reproduce:

1. Create the player
2. Destroy the player using destroy method
3. Check for event listeners

Expected behavior
Destroy method should remove all event listeners as described in the docs.

![PixelSnap 2021-07-04 at 18 26 33](https://user-images.githubusercontent.com/13521410/124471522-414b7400-dd9d-11eb-9d5c-68313d596350.png)

**Comment by rafa8626** [comment]
@draganpetos this should be fixed; please download the master branch and test it. Let me know if it all works as expected now. Thanks!

**Comment by draganpetos** [comment]
@rafa8626 tested with the latest script from the master branch and still seeing this issue.

When we instantiate the player, these are the listeners that get added:
![PixelSnap 2021-07-09 at 20 26 08](https://user-images.githubusercontent.com/13521410/125122644-04151800-e0f6-11eb-895e-40178d828416.png)

and these are the ones that get left behind after destroying the player:
![PixelSnap 2021-07-09 at 20 26 49](https://user-images.githubusercontent.com/13521410/125122711-18591500-e0f6-11eb-91db-06a9748029d5.png)

**Comment by rafa8626** [comment]
@draganpetos thanks for the heads up; do you have the reference of where those events are left. In your first screen I saw the location but in these new ones I can’t see it. That would help me to troubleshoot more quickly this

**Comment by rafa8626** [comment]
@draganpetos This should be fixed now; please confirm by downloading the master branch

**Comment by rafa8626** [comment]
@draganpetos can you provide me a CodePen to detect all the events not destroyed please? That way I can determine why it’s not happening

**Comment by rafa8626** [comment]
@draganpetos Please download the master branch and test this again; I integrated a way to successfully remove listeners. Please let me know if it worked for you

**Comment by draganpetos** [comment]
Hi @rafa8626 
I just tested with the latest released version and in our case, all of the listeners get removed properly, except for the loadedmetadata event.

![PixelSnap 2021-08-04 at 22 10 17](https://user-images.githubusercontent.com/13521410/128305509-2255d979-43a5-4b41-a383-ea1b0ff57a5e.png)

Thank you so much for this update!

**Comment by rafa8626** [comment]
@draganpetos thanks for the heads up; I’ll check this and set the fix in an oncoming release

**Comment by rafa8626** [comment]
@draganpetos please download the master brach and test one more time if that event is now gone for good. Let me know if it worked for you. Thanks!

**Comment by draganpetos** [comment]
Perfect! Just tested, and all the events get removed after calling destroy. 💪  😎

**Comment by rafa8626** [comment]
@draganpetos great! I may have the release ready tonight then; thanks for testing this!

**Comment by draganpetos** [comment]
@rafa8626 thank you, for all the new features and on an excellent player! 🙌

**Comment by rafa8626** [comment]
@draganpetos you are welcome! If you know more people that can star the project, I’d appreciate it, so the player keeps gaining popularity
