### ISSUE TITLE
fix chrome lighthouse Accessibility error

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#399]
Hi,
When i check player page with google chrome Lighthouse ,got this two error for accessibility tab.
Can you check them please?

![image](https://github.com/openplayerjs/openplayerjs/assets/13816403/00b80b20-4ac1-45ab-80ba-ee55e2224129)

I think they will fix with some text change

Best
Thanks

**Comment by rafa8626** [comment]
@foadabdollahi I’ll check this and get back to you; seems like I need to remove a role and add one to solve these 2 issues. Thanks for reporting this

**Comment by rafa8626** [comment]
@foadabdollahi I have fixed it and it should now return no Accessibility concerns from the player. Let me know if it works for you. The new version of the player has been released today

**Comment by foadabdollahi** [comment]
thanks
but i check them but issue not solved.

1. The "[aria-*] attributes" issue will solve with correct filling  aria-valuemax="NaN"
2. The "<frame> or <iframe> elements do not have a title" issue came from ads iframe and need title.
 
![image](https://github.com/openplayerjs/openplayerjs/assets/13816403/014d3e81-5cb7-4ad4-80cb-bbe1b65c0e9a)

**Comment by rafa8626** [comment]
@foadabdollahi could you share the page you are analyzing, since I checked this yesterday and I got 100% accessibility rate from Lighthouse?

**Comment by foadabdollahi** [comment]
@rafa8626 
Sure,

[https://nashrin.com/v/h3n4](https://nashrin.com/v/h3n4)

![image](https://github.com/openplayerjs/openplayerjs/assets/13816403/b5b0ae89-c4ff-4945-a4fc-649ac637b419)

**Comment by rafa8626** [comment]
@foadabdollahi I just pushed my changes in master but haven't released them yet. If you can install the branch on your side and verify this I'd appreciate it. This is what I see with the minimal setup and using your files:
<img width="1509" alt="Screenshot 2024-01-11 at 9 57 23 AM" src="https://github.com/openplayerjs/openplayerjs/assets/910829/3cea830e-2e1e-4ec0-88c0-7f6ed3862a5a">
Could you share your player configuration, so I can check the highlighted item?

**Comment by foadabdollahi** [comment]
Sure,



```
const option: PlayerOptions = {

        mode: "fit",
        // ads: { 
        //     src: "https://tavoos.net/services/vast/VRTCJo9q-PwnV-Auv4-PjUe-AQE6kQYmnFWk/126?format=VAST",
        //     language: "fa",
        //     debug: true,
        //     loop: false, 
        // },
        showLoaderOnInit: false, 
        detachMenus: true, 
        forceNative: false,
        useDeviceVolume: true,
        pauseOthers: true,
        labels: {
            auto: "اتوماتیک",
            captions: "زیر نویس",
            click: `برای صدا کلیک کنید`,
            fullscreen: "Fullscreen",
            lang: {
                fa: "فارسی"
            },
            levels: "تغییر کیفیت", 
            //live: "پخش زنده",
            mediaLevels: "تغییر کیفیت",
            mute: "بی‌صدا",
            off: "خاموش",
            pause: "متوقف",
            play: "پخش",
            progressRail: "Time Rail",
            progressSlider: "Time Slider",
            settings: "تنظیمات",
            speed: "سرعت پخش",
            speedNormal: "عادی",
            tap: `برای صدا دار کردن کلیک کنید`,
            toggleCaptions: "تغییر زیرنویس",
            unmute: `برای صدا کلیک کنید`,
            volume: "تنظیم صدا",
            volumeControl: "کنترل صدا",
            volumeSlider: "کنترل صدا",
        },
        onError: function onError(e) {
            // console.log("error", e);
        },
        // hls: {
        //     startLevel: -1,
        //     enableWorker: true,
        //     autoStartLoad: true,
        //     maxBufferLength: 30,
        //     maxMaxBufferLength: 30,
        //     emeEnabled: true,
        //     smoothQualityChange: true,
        //     overrideNative: true
        // },
        media: {
            pauseOnClick: true,
        },
        
        


    };


   player.addControl({
                    id: 'next',
                    position: "bottom-right",
                    showInAds: false,
                    type: "img",
                    alt:"بعدی",
                    custom: true,
                    icon: '/img/nexticon.svg',
                    title: "بعدی :" + next.title,
                    click: (e) => {
                        e.preventDefault();
                        //router.push(`/v/${next.uid}`);
                    },

                });
```

**Comment by rafa8626** [comment]
@foadabdollahi based on your configuration, the highlighted area is for Google Ads, and those are not set by the player. I enabled them and I was able to see the Ad but not the company slot. So that's a different element from your page unrelated to OpenPlayerJS. As per the iframe warning, this is created by IMA SDK (the library that renders the Ads) and it doesn't have a property/callback to set the iframe's title, so there's nothing I can do about it. I updated the master branch to reflect a minor fix for the `alt` attribute. Let me know if that worked for you
