### ISSUE TITLE
startVolume bug

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#48]
Hello rafa
When using the startVolume setting.
The image of the sound level is incorrectly displayed.
https://codepen.io/anon/pen/jXXMBm
![Imgur](https://i.imgur.com/fj5Dy2t.png)

**Comment by rafa8626** [comment]
@supersh86 check the master branch and confirm it is fixed. Thanks for reporting this

**Comment by supersh86** [comment]
That would not create a single theme.
I still have a problem after adding a button.
Sometimes, fullscreen mode stops working.

When you click the console gives an error.
openplayer.min.js? v = 39: 1 Uncaught (in promise) TypeError: Document not active
     at e.value (openplayer.min.js? v = 39: 1)
     at e.clickEvent (openplayer.min.js? v = 39: 1)

**Comment by rafa8626** [comment]
Is this replicable in the codepen you shared today?

**Comment by rafa8626** [comment]
@supersh86 I'll need more details about the button issue you are experiencing. Please open a different issue, since the scope of this one has been resolved.
